name: survey-tentacles

services:
  tentacles-db:
    image: postgres:17-alpine
    container_name: tentacles-db
    restart: unless-stopped

    environment:
      POSTGRES_DB: tentacles
      POSTGRES_USER: ${TENTACLES_USERNAME}
      POSTGRES_PASSWORD: ${TENTACLES_PASSWORD}

    volumes:
      - tentacles-postgres-data:/var/lib/postgresql/data

  tentacles:
    image: ghcr.io/eiredrake/survey_tentacles:v1.5.5
    container_name: tentacles
    restart: unless-stopped

    depends_on:
      - tentacles-db

    environment:
      TENTACLES_DB_URL: jdbc:postgresql://tentacles-db:5432/tentacles
      TENTACLES_USERNAME: ${TENTACLES_USERNAME}
      TENTACLES_PASSWORD: ${TENTACLES_PASSWORD}

      AUTHENTIK_CLIENT_ID: ${AUTHENTIK_CLIENT_ID}
      AUTHENTIK_CLIENT_SECRET: ${AUTHENTIK_CLIENT_SECRET}
      AUTHENTIK_ISSUER_URI: ${AUTHENTIK_ISSUER_URI}

      TENTACLES_PUBLIC_BASE_URL: ${TENTACLES_PUBLIC_BASE_URL}
      TENTACLES_UPLOAD_DIR: /app/uploads
    ports:
      - "8080:8080"

    volumes:
      - tentacles-upload-data:/app/uploads      

volumes:
  tentacles-postgres-data:
  tentacles-upload-data:  