spring.application.name=tentacles

spring.datasource.url=jdbc:postgresql://localhost:5433/tentacles
spring.datasource.username=${TENTACLES_USERNAME}
spring.datasource.password=${TENTACLES_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.security.oauth2.client.registration.authentik.client-id=${AUTHENTIK_CLIENT_ID}
spring.security.oauth2.client.registration.authentik.client-secret=${AUTHENTIK_CLIENT_SECRET}
spring.security.oauth2.client.registration.authentik.scope=openid,profile,email

spring.security.oauth2.client.provider.authentik.issuer-uri=https://auth.foundationsrpg.org/application/o/tentacles/

logging.level.org.springframework.security=DEBUG
server.forward-headers-strategy=framework
tentacles.public-base-url=${TENTACLES_PUBLIC_BASE_URL:http://localhost:8080}