spring.application.name=tentacles

spring.datasource.url=jdbc:postgresql://localhost:5433/tentacles
spring.datasource.username=tentacles
spring.datasource.password=tentacles_dev_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect